version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 9000:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
      # - MYSQL_ROOT_PASSWORD=password
